"""Rename Endpoints model to Policy

Revision ID: 1db521c2cb42
Revises: 03880a725e50
Create Date: 2026-04-07 21:17:55.002074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1db521c2cb42'
down_revision: Union[str, Sequence[str], None] = '03880a725e50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('replacement_name', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policies_action'), 'policies', ['action'], unique=False)
    op.create_index(op.f('ix_policies_id'), 'policies', ['id'], unique=False)
    op.create_index(op.f('ix_policies_name'), 'policies', ['name'], unique=True)
    op.create_index(op.f('ix_policies_status'), 'policies', ['status'], unique=False)
    op.drop_index(op.f('ix_endpoints_action'), table_name='endpoints')
    op.drop_index(op.f('ix_endpoints_id'), table_name='endpoints')
    op.drop_index(op.f('ix_endpoints_name'), table_name='endpoints')
    op.drop_index(op.f('ix_endpoints_status'), table_name='endpoints')
    op.drop_table('endpoints')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endpoints',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=10), nullable=False),
    sa.Column('expiry_date', sa.DATETIME(), nullable=True),
    sa.Column('replacement_name', sa.VARCHAR(), nullable=True),
    sa.Column('action', sa.VARCHAR(length=5), nullable=False),
    sa.Column('owner_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_endpoints_status'), 'endpoints', ['status'], unique=False)
    op.create_index(op.f('ix_endpoints_name'), 'endpoints', ['name'], unique=1)
    op.create_index(op.f('ix_endpoints_id'), 'endpoints', ['id'], unique=False)
    op.create_index(op.f('ix_endpoints_action'), 'endpoints', ['action'], unique=False)
    op.drop_index(op.f('ix_policies_status'), table_name='policies')
    op.drop_index(op.f('ix_policies_name'), table_name='policies')
    op.drop_index(op.f('ix_policies_id'), table_name='policies')
    op.drop_index(op.f('ix_policies_action'), table_name='policies')
    op.drop_table('policies')
    # ### end Alembic commands ###
