"""Create Endpoints model take 2

Revision ID: bcb82d893416
Revises: 819bda584c80
Create Date: 2026-03-18 20:42:08.829820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcb82d893416'
down_revision: Union[str, Sequence[str], None] = '819bda584c80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('active', 'deprecated', 'inactive', name='statusenum'), nullable=False),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('replacement_name', sa.String(), nullable=True),
    sa.Column('action', sa.Enum('let', 'block', name='actionenum'), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_endpoints_action'), 'endpoints', ['action'], unique=False)
    op.create_index(op.f('ix_endpoints_id'), 'endpoints', ['id'], unique=False)
    op.create_index(op.f('ix_endpoints_name'), 'endpoints', ['name'], unique=True)
    op.create_index(op.f('ix_endpoints_status'), 'endpoints', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_endpoints_status'), table_name='endpoints')
    op.drop_index(op.f('ix_endpoints_name'), table_name='endpoints')
    op.drop_index(op.f('ix_endpoints_id'), table_name='endpoints')
    op.drop_index(op.f('ix_endpoints_action'), table_name='endpoints')
    op.drop_table('endpoints')
    # ### end Alembic commands ###
